# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - appsrv-bhj-rebates-eastus2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          # Install only production dependencies for deployment
          npm ci --only=production
          
      - name: Run deployment script
        run: |
          chmod +x deploy.sh
          ./deploy.sh

      - name: Prepare deployment package
        run: |
          mkdir deployment-package
          cp package.json deployment-package/
          cp package-lock.json deployment-package/
          cp server.js deployment-package/
          cp .deployment deployment-package/
          cp deploy.cmd deployment-package/
          cp -r dist/ deployment-package/
          cp -r node_modules/ deployment-package/
          # Add deployment timestamp and cache buster to force fresh deployment
          echo "DEPLOY_TIMESTAMP=$(date +%Y%m%d_%H%M%S)" > deployment-package/.env.deploy
          echo "CACHE_BUST=$(date +%s)" >> deployment-package/.env.deploy
          # Create a deployment marker file
          echo "Validation mock data updated: $(date)" > deployment-package/DEPLOYMENT_MARKER.txt
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment-package/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D5E6692B870A46F39C313DF0C03FFD29 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BFEB7B6A164446B6B10C758DBB55C0D4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8D7131F6299946868957C0635076847F }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'appsrv-bhj-rebates-eastus2'
          slot-name: 'Production'
          package: .
          clean: true
          restart: true
          